"""
tagger/tag_categories.py

Detailed subcategory mapping that replicates avan06/wd-tagger-images categorization.
Maps individual tags to human-friendly subcategories.

Subcategory display order (matching the original UI):
  Appearance Status, Character Design, explicit,
  Upper Body, Action Pose, Outdoor, Lower Body,
  Head, Facial Expression, Censorship, Creature,
  Background, Others, Unclassified
"""

from __future__ import annotations

# ─── Subcategory definitions ──────────────────────────────────────────────────
# Order matters: it determines the display order in the UI

SUBCATEGORY_ORDER = [
    "Appearance Status",
    "Character Design",
    "explicit",
    "Upper Body",
    "Action Pose",
    "Outdoor",
    "Lower Body",
    "Head",
    "Facial Expression",
    "Censorship",
    "Creature",
    "Background",
    "Hair",
    "Eyes",
    "Clothing",
    "Accessories",
    "Others",
    "Unclassified",
]

# ─── Tag → Subcategory lookup (general/meta tags) ─────────────────────────────
# Keys are tag names AS THEY APPEAR in selected_tags.csv (with underscores)

TAG_SUBCATEGORY: dict[str, str] = {

    # ── Appearance Status ─────────────────────────────────────────────────
    "nude": "Appearance Status",
    "completely_nude": "Appearance Status",
    "topless": "Appearance Status",
    "bottomless": "Appearance Status",
    "naked": "Appearance Status",
    "partially_clothed": "Appearance Status",
    "clothed": "Appearance Status",
    "undressing": "Appearance Status",
    "clothes_removed": "Appearance Status",
    "shiny_skin": "Appearance Status",
    "wet": "Appearance Status",
    "sweating": "Appearance Status",
    "blush": "Appearance Status",
    "veins": "Appearance Status",
    "tan": "Appearance Status",
    "tan_lines": "Appearance Status",
    "dark_skin": "Appearance Status",
    "light_skin": "Appearance Status",
    "very_dark_skin": "Appearance Status",
    "pale_skin": "Appearance Status",
    "oiled_skin": "Appearance Status",
    "covered_in_cum": "Appearance Status",
    "cum_on_body": "Appearance Status",
    "cum_on_breasts": "Appearance Status",
    "partially_submerged": "Appearance Status",
    "submerged": "Appearance Status",
    "body_blush": "Appearance Status",
    "blushing": "Appearance Status",
    "wet_clothes": "Appearance Status",
    "see-through": "Appearance Status",
    "shiny": "Appearance Status",
    "shiny_hair": "Appearance Status",
    "body_writing": "Appearance Status",

    # ── Character Design ──────────────────────────────────────────────────
    "1girl": "Character Design",
    "2girls": "Character Design",
    "3girls": "Character Design",
    "4girls": "Character Design",
    "5girls": "Character Design",
    "6+girls": "Character Design",
    "multiple_girls": "Character Design",
    "1boy": "Character Design",
    "2boys": "Character Design",
    "3boys": "Character Design",
    "multiple_boys": "Character Design",
    "1other": "Character Design",
    "2others": "Character Design",
    "male_focus": "Character Design",
    "female_focus": "Character Design",
    "solo": "Character Design",
    "solo_focus": "Character Design",
    "group": "Character Design",
    "couple": "Character Design",
    "futanari": "Character Design",
    "trap": "Character Design",
    "androgynous": "Character Design",
    "animal_ears": "Character Design",
    "cat_ears": "Character Design",
    "fox_ears": "Character Design",
    "rabbit_ears": "Character Design",
    "dog_ears": "Character Design",
    "kemonomimi_mode": "Character Design",
    "tail": "Character Design",
    "cat_tail": "Character Design",
    "fox_tail": "Character Design",
    "rabbit_tail": "Character Design",
    "wings": "Character Design",
    "horns": "Character Design",
    "demon_horns": "Character Design",
    "halo": "Character Design",
    "elf": "Character Design",
    "pointy_ears": "Character Design",
    "monster_girl": "Character Design",
    "lamia": "Character Design",
    "mermaid": "Character Design",
    "centaur": "Character Design",

    # ── explicit ──────────────────────────────────────────────────────────
    "sex": "explicit",
    "vaginal": "explicit",
    "anal": "explicit",
    "oral": "explicit",
    "fellatio": "explicit",
    "cunnilingus": "explicit",
    "paizuri": "explicit",
    "handjob": "explicit",
    "footjob": "explicit",
    "fisting": "explicit",
    "penetration": "explicit",
    "penis": "explicit",
    "vagina": "explicit",
    "pussy": "explicit",
    "anus": "explicit",
    "nipples": "explicit",
    "erection": "explicit",
    "cum": "explicit",
    "ejaculation": "explicit",
    "cum_in_mouth": "explicit",
    "cum_in_pussy": "explicit",
    "cum_in_ass": "explicit",
    "internal_cumshot": "explicit",
    "x-ray": "explicit",
    "orgasm": "explicit",
    "rape": "explicit",
    "gangbang": "explicit",
    "group_sex": "explicit",
    "threesome": "explicit",
    "ffm_threesome": "explicit",
    "mmf_threesome": "explicit",
    "cooperative_fellatio": "explicit",
    "double_penetration": "explicit",
    "interracial": "explicit",
    "hetero": "explicit",
    "yuri": "explicit",
    "yaoi": "explicit",
    "masturbation": "explicit",
    "fingering": "explicit",
    "vibrator": "explicit",
    "dildo": "explicit",
    "sex_toy": "explicit",
    "squirting": "explicit",
    "tribadism": "explicit",
    "licking_penis": "explicit",
    "licking_pussy": "explicit",
    "69": "explicit",
    "mmf": "explicit",
    "large_penis": "explicit",
    "veiny_penis": "explicit",
    "small_penis": "explicit",
    "testicles": "explicit",
    "balls": "explicit",
    "penis_in_mouth": "explicit",
    "mixed-sex_bathing": "explicit",
    "shared_bathing": "explicit",

    # ── Upper Body ────────────────────────────────────────────────────────
    "breasts": "Upper Body",
    "large_breasts": "Upper Body",
    "small_breasts": "Upper Body",
    "medium_breasts": "Upper Body",
    "huge_breasts": "Upper Body",
    "flat_chest": "Upper Body",
    "very_small_breasts": "Upper Body",
    "gigantic_breasts": "Upper Body",
    "cleavage": "Upper Body",
    "breast_hold": "Upper Body",
    "breast_press": "Upper Body",
    "breast_grab": "Upper Body",
    "breast_squeeze": "Upper Body",
    "breast_lift": "Upper Body",
    "areolae": "Upper Body",
    "dark_areolae": "Upper Body",
    "large_areolae": "Upper Body",
    "inverted_nipples": "Upper Body",
    "puffy_nipples": "Upper Body",
    "nipple_piercing": "Upper Body",
    "toned": "Upper Body",
    "muscular": "Upper Body",
    "abs": "Upper Body",
    "belly_button": "Upper Body",
    "navel": "Upper Body",
    "stomach": "Upper Body",
    "midriff": "Upper Body",
    "collarbone": "Upper Body",
    "armpits": "Upper Body",
    "shoulders": "Upper Body",
    "back": "Upper Body",
    "arms": "Upper Body",
    "hands": "Upper Body",
    "fingers": "Upper Body",
    "waist": "Upper Body",
    "ribs": "Upper Body",
    "spine": "Upper Body",

    # ── Action Pose ───────────────────────────────────────────────────────
    "looking_at_viewer": "Action Pose",
    "looking_away": "Action Pose",
    "looking_back": "Action Pose",
    "looking_down": "Action Pose",
    "looking_up": "Action Pose",
    "looking_to_the_side": "Action Pose",
    "pov": "Action Pose",
    "from_above": "Action Pose",
    "from_below": "Action Pose",
    "from_behind": "Action Pose",
    "from_side": "Action Pose",
    "pov_crotch": "Action Pose",
    "pov_feet": "Action Pose",
    "standing": "Action Pose",
    "sitting": "Action Pose",
    "lying": "Action Pose",
    "kneeling": "Action Pose",
    "squatting": "Action Pose",
    "crouching": "Action Pose",
    "on_all_fours": "Action Pose",
    "all_fours": "Action Pose",
    "doggystyle": "Action Pose",
    "missionary": "Action Pose",
    "riding": "Action Pose",
    "reverse_cowgirl_position": "Action Pose",
    "cowgirl_position": "Action Pose",
    "spread_legs": "Action Pose",
    "legs_up": "Action Pose",
    "standing_sex": "Action Pose",
    "bent_over": "Action Pose",
    "arched_back": "Action Pose",
    "arms_up": "Action Pose",
    "arms_behind_back": "Action Pose",
    "arms_behind_head": "Action Pose",
    "hand_on_hip": "Action Pose",
    "hand_on_own_chest": "Action Pose",
    "licking": "Action Pose",
    "licking_lips": "Action Pose",
    "sucking": "Action Pose",
    "kissing": "Action Pose",
    "sleeping": "Action Pose",
    "running": "Action Pose",
    "walking": "Action Pose",
    "jumping": "Action Pose",
    "dancing": "Action Pose",
    "stretching": "Action Pose",
    "twintails_pose": "Action Pose",
    "peace_sign": "Action Pose",
    "v_arms": "Action Pose",
    "waving": "Action Pose",

    # ── Outdoor ───────────────────────────────────────────────────────────
    "outdoors": "Outdoor",
    "outside": "Outdoor",
    "nature": "Outdoor",
    "forest": "Outdoor",
    "field": "Outdoor",
    "beach": "Outdoor",
    "ocean": "Outdoor",
    "sea": "Outdoor",
    "pool": "Outdoor",
    "river": "Outdoor",
    "lake": "Outdoor",
    "mountain": "Outdoor",
    "sky": "Outdoor",
    "clouds": "Outdoor",
    "snow": "Outdoor",
    "rain": "Outdoor",
    "grass": "Outdoor",
    "park": "Outdoor",
    "garden": "Outdoor",
    "rooftop": "Outdoor",
    "street": "Outdoor",
    "city": "Outdoor",
    "night": "Outdoor",
    "day": "Outdoor",
    "sunset": "Outdoor",
    "sunrise": "Outdoor",
    "full_moon": "Outdoor",
    "stars": "Outdoor",
    "onsen": "Outdoor",
    "hot_spring": "Outdoor",
    "waterfall": "Outdoor",
    "cliff": "Outdoor",

    # ── Lower Body ────────────────────────────────────────────────────────
    "ass": "Lower Body",
    "huge_ass": "Lower Body",
    "large_ass": "Lower Body",
    "plump": "Lower Body",
    "ass_grab": "Lower Body",
    "spanking": "Lower Body",
    "thighs": "Lower Body",
    "thick_thighs": "Lower Body",
    "thigh_gap": "Lower Body",
    "legs": "Lower Body",
    "long_legs": "Lower Body",
    "short_legs": "Lower Body",
    "feet": "Lower Body",
    "toes": "Lower Body",
    "barefoot": "Lower Body",
    "soles": "Lower Body",
    "ankle": "Lower Body",
    "knees": "Lower Body",
    "hips": "Lower Body",
    "wide_hips": "Lower Body",
    "narrow_waist": "Lower Body",
    "curvy": "Lower Body",
    "groin": "Lower Body",
    "pubic_hair": "Lower Body",
    "pubic_tattoo": "Lower Body",

    # ── Head ──────────────────────────────────────────────────────────────
    "1head": "Head",
    "face": "Head",
    "portrait": "Head",
    "close-up": "Head",
    "close_up": "Head",
    "face_focus": "Head",
    "head": "Head",
    "forehead": "Head",
    "cheeks": "Head",
    "chin": "Head",
    "jaw": "Head",
    "neck": "Head",
    "ears": "Head",
    "nose": "Head",
    "lips": "Head",
    "large_nose": "Head",
    "freckles": "Head",
    "mole": "Head",
    "mole_under_eye": "Head",
    "mole_on_breast": "Head",
    "birthmark": "Head",
    "scar": "Head",
    "tattoo": "Head",
    "headband": "Head",
    "tiara": "Head",
    "crown": "Head",
    "veil": "Head",
    "hat": "Head",
    "hair_ornament": "Head",
    "forehead_mark": "Head",

    # ── Facial Expression ─────────────────────────────────────────────────
    "smile": "Facial Expression",
    "grin": "Facial Expression",
    "smirk": "Facial Expression",
    "frown": "Facial Expression",
    "angry": "Facial Expression",
    "sad": "Facial Expression",
    "crying": "Facial Expression",
    "tears": "Facial Expression",
    "surprised": "Facial Expression",
    "shocked": "Facial Expression",
    "scared": "Facial Expression",
    "embarrassed": "Facial Expression",
    "ahegao": "Facial Expression",
    "orgasm_face": "Facial Expression",
    "tongue": "Facial Expression",
    "tongue_out": "Facial Expression",
    "open_mouth": "Facial Expression",
    "closed_mouth": "Facial Expression",
    "half-closed_eyes": "Facial Expression",
    "wink": "Facial Expression",
    "pout": "Facial Expression",
    "smug": "Facial Expression",
    "seductive_smile": "Facial Expression",
    "expressionless": "Facial Expression",
    "o_o": "Facial Expression",
    ">_<": "Facial Expression",
    "^_^": "Facial Expression",
    "=_=": "Facial Expression",
    "evil_smile": "Facial Expression",
    "naughty_face": "Facial Expression",
    "drooling": "Facial Expression",
    "wavy_mouth": "Facial Expression",
    "spoken_heart": "Facial Expression",

    # ── Censorship ────────────────────────────────────────────────────────
    "censored": "Censorship",
    "uncensored": "Censorship",
    "mosaic_censoring": "Censorship",
    "bar_censor": "Censorship",
    "convenient_censoring": "Censorship",
    "loli": "Censorship",
    "shota": "Censorship",

    # ── Creature ──────────────────────────────────────────────────────────
    "dog": "Creature",
    "cat": "Creature",
    "fox": "Creature",
    "horse": "Creature",
    "dragon": "Creature",
    "wolf": "Creature",
    "rabbit": "Creature",
    "bird": "Creature",
    "snake": "Creature",
    "monster": "Creature",
    "alien": "Creature",
    "slime": "Creature",
    "tentacles": "Creature",
    "insect": "Creature",
    "spider": "Creature",
    "fish": "Creature",
    "creature": "Creature",
    "animal": "Creature",

    # ── Background ────────────────────────────────────────────────────────
    "indoors": "Background",
    "bedroom": "Background",
    "bathroom": "Background",
    "kitchen": "Background",
    "living_room": "Background",
    "classroom": "Background",
    "office": "Background",
    "gym": "Background",
    "hospital": "Background",
    "prison": "Background",
    "dungeon": "Background",
    "laboratory": "Background",
    "library": "Background",
    "church": "Background",
    "castle": "Background",
    "inn": "Background",
    "bar": "Background",
    "store": "Background",
    "locker_room": "Background",
    "changing_room": "Background",
    "pool_side": "Background",
    "hallway": "Background",
    "stairs": "Background",
    "window": "Background",
    "curtains": "Background",
    "bed": "Background",
    "couch": "Background",
    "table": "Background",
    "chair": "Background",
    "floor": "Background",
    "wall": "Background",
    "water": "Background",
    "ripples": "Background",
    "steam": "Background",
    "smoke": "Background",
    "fire": "Background",
    "light": "Background",
    "shadow": "Background",
    "bokeh": "Background",
    "simple_background": "Background",
    "white_background": "Background",
    "black_background": "Background",
    "gradient_background": "Background",
    "abstract_background": "Background",

    # ── Hair ──────────────────────────────────────────────────────────────
    "long_hair": "Hair",
    "short_hair": "Hair",
    "medium_hair": "Hair",
    "very_long_hair": "Hair",
    "bob_cut": "Hair",
    "twin_tails": "Hair",
    "twintails": "Hair",
    "ponytail": "Hair",
    "side_ponytail": "Hair",
    "braid": "Hair",
    "twin_braids": "Hair",
    "bun": "Hair",
    "hair_bun": "Hair",
    "double_bun": "Hair",
    "pixie_cut": "Hair",
    "ahoge": "Hair",
    "drill_hair": "Hair",
    "ringlets": "Hair",
    "wavy_hair": "Hair",
    "curly_hair": "Hair",
    "straight_hair": "Hair",
    "messy_hair": "Hair",
    "sidelocks": "Hair",
    "bangs": "Hair",
    "parted_bangs": "Hair",
    "blunt_bangs": "Hair",
    "swept_bangs": "Hair",
    "hair_over_one_eye": "Hair",
    "hair_over_eyes": "Hair",
    "blonde_hair": "Hair",
    "brown_hair": "Hair",
    "black_hair": "Hair",
    "white_hair": "Hair",
    "silver_hair": "Hair",
    "grey_hair": "Hair",
    "red_hair": "Hair",
    "pink_hair": "Hair",
    "blue_hair": "Hair",
    "green_hair": "Hair",
    "purple_hair": "Hair",
    "orange_hair": "Hair",
    "multicolored_hair": "Hair",
    "gradient_hair": "Hair",
    "streaked_hair": "Hair",
    "dark_hair": "Hair",
    "light_hair": "Hair",
    "wet_hair": "Hair",

    # ── Eyes ──────────────────────────────────────────────────────────────
    "blue_eyes": "Eyes",
    "red_eyes": "Eyes",
    "green_eyes": "Eyes",
    "yellow_eyes": "Eyes",
    "brown_eyes": "Eyes",
    "purple_eyes": "Eyes",
    "pink_eyes": "Eyes",
    "orange_eyes": "Eyes",
    "black_eyes": "Eyes",
    "grey_eyes": "Eyes",
    "teal_eyes": "Eyes",
    "white_eyes": "Eyes",
    "heterochromia": "Eyes",
    "multicolored_eyes": "Eyes",
    "glowing_eyes": "Eyes",
    "slit_pupils": "Eyes",
    "heart_pupils": "Eyes",
    "spiral_eyes": "Eyes",
    "star_eyes": "Eyes",
    "empty_eyes": "Eyes",
    "glasses": "Eyes",
    "sunglasses": "Eyes",
    "eyebrows": "Eyes",
    "thick_eyebrows": "Eyes",
    "thin_eyebrows": "Eyes",
    "eyelashes": "Eyes",
    "eyeshadow": "Eyes",
    "mascara": "Eyes",

    # ── Clothing ──────────────────────────────────────────────────────────
    "uniform": "Clothing",
    "school_uniform": "Clothing",
    "dress": "Clothing",
    "skirt": "Clothing",
    "short_skirt": "Clothing",
    "miniskirt": "Clothing",
    "long_skirt": "Clothing",
    "pants": "Clothing",
    "jeans": "Clothing",
    "shorts": "Clothing",
    "shirt": "Clothing",
    "t-shirt": "Clothing",
    "sweater": "Clothing",
    "hoodie": "Clothing",
    "jacket": "Clothing",
    "coat": "Clothing",
    "suit": "Clothing",
    "tie": "Clothing",
    "tie_clip": "Clothing",
    "bikini": "Clothing",
    "swimsuit": "Clothing",
    "one-piece_swimsuit": "Clothing",
    "lingerie": "Clothing",
    "bra": "Clothing",
    "panties": "Clothing",
    "thong": "Clothing",
    "stockings": "Clothing",
    "thighhighs": "Clothing",
    "pantyhose": "Clothing",
    "socks": "Clothing",
    "shoes": "Clothing",
    "boots": "Clothing",
    "heels": "Clothing",
    "high_heels": "Clothing",
    "sneakers": "Clothing",
    "sandals": "Clothing",
    "apron": "Clothing",
    "maid": "Clothing",
    "kimono": "Clothing",
    "yukata": "Clothing",
    "qipao": "Clothing",
    "armor": "Clothing",
    "cape": "Clothing",
    "gloves": "Clothing",
    "collar": "Clothing",
    "choker": "Clothing",
    "leotard": "Clothing",
    "bodysuit": "Clothing",
    "latex": "Clothing",
    "torn_clothes": "Clothing",

    # ── Accessories ───────────────────────────────────────────────────────
    "earrings": "Accessories",
    "necklace": "Accessories",
    "bracelet": "Accessories",
    "ring": "Accessories",
    "watch": "Accessories",
    "bag": "Accessories",
    "umbrella": "Accessories",
    "sword": "Accessories",
    "gun": "Accessories",
    "bow_(weapon)": "Accessories",
    "staff": "Accessories",
    "book": "Accessories",
    "flower": "Accessories",
    "rose": "Accessories",
    "cigarette": "Accessories",
    "phone": "Accessories",
    "cellphone": "Accessories",
    "camera": "Accessories",
    "microphone": "Accessories",
    "heart": "Accessories",
    "star": "Accessories",
    "cross": "Accessories",
    "chain": "Accessories",
    "leash": "Accessories",
    "blindfold": "Accessories",
    "handcuffs": "Accessories",
    "rope": "Accessories",
    "ribbon": "Accessories",
    "bow": "Accessories",

    # ── Others (meta/social) ──────────────────────────────────────────────
    "patreon_username": "Others",
    "patreon_logo": "Others",
    "web_address": "Others",
    "watermark": "Others",
    "text": "Others",
    "english_text": "Others",
    "japanese_text": "Others",
    "signature": "Others",
    "artist_name": "Others",
    "character_name": "Others",
    "logo": "Others",
    "speech_bubble": "Others",
    "thought_bubble": "Others",
    "subtitled": "Others",
    "translated": "Others",
    "hard_translated": "Others",
    "poorly_translated": "Others",
    "third-party_edit": "Others",
    "highres": "Others",
    "absurdres": "Others",
    "lowres": "Others",
    "bad_anatomy": "Others",
    "bad_hands": "Others",
    "extra_fingers": "Others",
    "missing_fingers": "Others",
    "normal_quality": "Others",
    "best_quality": "Others",
    "masterpiece": "Others",
    "photo": "Others",
    "realistic": "Others",
    "3d": "Others",
    "comic": "Others",
    "manga": "Others",
    "sketch": "Others",
    "monochrome": "Others",
    "greyscale": "Others",
    "colorful": "Others",
    "multiple_views": "Others",
    "reference_sheet": "Others",
    "cropped": "Others",
    "bordered": "Others",
    "framed": "Others",
    "panel": "Others",
}


# ─── Category WD → subcategory mapping for non-general tags ──────────────────

WD_CATEGORY_TO_SUB = {
    "rating":    "rating",   # handled separately, shown at top if enabled
    "artist":    "Others",
    "copyright": "Others",
    "character": "Character Design",
    "meta":      "Others",
}


def get_subcategory(tag_name: str, wd_category: str) -> str:
    """
    Return the subcategory for a given tag.
    First checks the explicit lookup table, then falls back
    to WD category mapping, and finally 'Unclassified'.
    """
    # Check explicit mapping (tag name with underscores)
    sub = TAG_SUBCATEGORY.get(tag_name)
    if sub:
        return sub

    # For non-general WD categories
    sub = WD_CATEGORY_TO_SUB.get(wd_category)
    if sub and sub != "Unclassified":
        return sub

    return "Unclassified"
